[build]
  command = "npm install && npm run postinstall"
  functions = "api"
  publish = "public"

[[redirects]]
  from = "/fetch"
  to = "/.netlify/functions/fetch"
  status = 200

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
