[build]
  command = "npm install"
  functions = "api"
  publish = "public"

[[redirects]]
  from = "/fetch/*"
  to = "/.netlify/functions/fetch/:splat"
  status = 200

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
