[build]
  command = "npm install"
  functions = "api"
  publish = "public"

[[redirects]]
  from = "/cheerio-fetch"
  to = "/.netlify/functions/cheerio-fetcher"
  status = 200

[[redirects]]
  from = "/cheerio-fetch/*"
  to = "/.netlify/functions/cheerio-fetcher/:splat"
  status = 200
